engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.rb"
exclude_paths:
  - config/
  - db/
  - spec/
  - app/docs/
