---

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - app/**/*
    - lib/**/*
    - confg/**/*
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - app/views/**/*
    - app/assets/**/*

Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/LineLength:
  Max: 120
