AllCops:
 Include:
   - Rakefile
   - config.ru
 Exclude:
   - db/schema.rb
 TargetRubyVersion: 2.4
Documentation:
 Enabled: false
Style/IfUnlessModifier:
 MaxLineLength: 120
Metrics/MethodLength:
 Enabled: false
Style/Documentation:
 Enabled: false
Metrics/AbcSize:
 Enabled: false
Metrics/ClassLength:
 Enabled: false
Metrics/LineLength:
 Enabled: false
Style/RescueModifier:
 Enabled: false
Metrics/LineLength:
 Max: 120
