language: ruby
rvm: 2.6.3
script:
  - bundle exec $CHECK

matrix:
  include:
    - stage: RSpec tests
      services:
        - postgresql
      before_script:
        - psql -c 'create database mentors4me_api_test;' -U postgres
        - "bundle exec rake db:migrate"
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      env: CHECK="rspec"
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: Rubocop check
      env: CHECK="rubocop"
