name: Main Workflow

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Rubocop Check
        run: |
          sudo apt-get install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop

  secrets_check:
    runs-on: ubuntu-latest

    steps:
      - uses: docker://cdssnc/seekret-github-action
