name: Main Workflow

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Rubocop Check
        run: |
          sudo apt-get install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop

  secrets_check:
    runs-on: ubuntu-latest

    steps:
      - uses: docker://cdssnc/seekret-github-action
